version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: server/dockerfile
    container_name: stream-machine-map-grpc-server
    ports:
      - "50051:50051"
    networks:
      - stream-machine-map-network

  ws-proxy:
    build:
      context: .
      dockerfile: server/ws-proxy/dockerfile
    container_name: stream-machine-map-ws-proxy
    ports: "3001:3001"
    depends_on:
      - grpc-server
    networks:
      - stream-machine-map-network
    environment:
      - GRPC_SERVER=grpc-server:50051

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      container_name: stream-machine-map-frontend
      ports:
        - "80:80"
      depends_one:
        - ws-prox
      network:
        - stream-machine-map-network

networks:
  stream-machine-map-network:
    driver: bridge