// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/machine_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location      *GPS                   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	FuelLevel     float32                `protobuf:"fixed32,3,opt,name=fuel_level,json=fuelLevel,proto3" json:"fuel_level,omitempty"`
	IsPaused      bool                   `protobuf:"varint,4,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_proto_machine_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_proto_machine_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Machine) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Machine) GetLocation() *GPS {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Machine) GetFuelLevel() float32 {
	if x != nil {
		return x.FuelLevel
	}
	return 0
}

func (x *Machine) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type GPS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPS) Reset() {
	*x = GPS{}
	mi := &file_proto_machine_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPS) ProtoMessage() {}

func (x *GPS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPS.ProtoReflect.Descriptor instead.
func (*GPS) Descriptor() ([]byte, []int) {
	return file_proto_machine_stream_proto_rawDescGZIP(), []int{1}
}

func (x *GPS) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GPS) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GPS) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

type MachineStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineStreamRequest) Reset() {
	*x = MachineStreamRequest{}
	mi := &file_proto_machine_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStreamRequest) ProtoMessage() {}

func (x *MachineStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStreamRequest.ProtoReflect.Descriptor instead.
func (*MachineStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_stream_proto_rawDescGZIP(), []int{2}
}

var File_proto_machine_stream_proto protoreflect.FileDescriptor

const file_proto_machine_stream_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/machine_stream.proto\x12\x05proto\"}\n" +
	"\aMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12&\n" +
	"\blocation\x18\x02 \x01(\v2\n" +
	".proto.GPSR\blocation\x12\x1d\n" +
	"\n" +
	"fuel_level\x18\x03 \x01(\x02R\tfuelLevel\x12\x1b\n" +
	"\tis_paused\x18\x04 \x01(\bR\bisPaused\";\n" +
	"\x03GPS\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x02R\x03alt\"\x16\n" +
	"\x14MachineStreamRequest2\xa6\x01\n" +
	"\n" +
	"MachineMap\x12)\n" +
	"\x05Pause\x12\x0e.proto.Machine\x1a\x0e.proto.Machine\"\x00\x12+\n" +
	"\aUnPause\x12\x0e.proto.Machine\x1a\x0e.proto.Machine\"\x00\x12@\n" +
	"\rMachineStream\x12\x1b.proto.MachineStreamRequest\x1a\x0e.proto.Machine\"\x000\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_machine_stream_proto_rawDescOnce sync.Once
	file_proto_machine_stream_proto_rawDescData []byte
)

func file_proto_machine_stream_proto_rawDescGZIP() []byte {
	file_proto_machine_stream_proto_rawDescOnce.Do(func() {
		file_proto_machine_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_machine_stream_proto_rawDesc), len(file_proto_machine_stream_proto_rawDesc)))
	})
	return file_proto_machine_stream_proto_rawDescData
}

var file_proto_machine_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_machine_stream_proto_goTypes = []any{
	(*Machine)(nil),              // 0: proto.Machine
	(*GPS)(nil),                  // 1: proto.GPS
	(*MachineStreamRequest)(nil), // 2: proto.MachineStreamRequest
}
var file_proto_machine_stream_proto_depIdxs = []int32{
	1, // 0: proto.Machine.location:type_name -> proto.GPS
	0, // 1: proto.MachineMap.Pause:input_type -> proto.Machine
	0, // 2: proto.MachineMap.UnPause:input_type -> proto.Machine
	2, // 3: proto.MachineMap.MachineStream:input_type -> proto.MachineStreamRequest
	0, // 4: proto.MachineMap.Pause:output_type -> proto.Machine
	0, // 5: proto.MachineMap.UnPause:output_type -> proto.Machine
	0, // 6: proto.MachineMap.MachineStream:output_type -> proto.Machine
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_machine_stream_proto_init() }
func file_proto_machine_stream_proto_init() {
	if File_proto_machine_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_machine_stream_proto_rawDesc), len(file_proto_machine_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_machine_stream_proto_goTypes,
		DependencyIndexes: file_proto_machine_stream_proto_depIdxs,
		MessageInfos:      file_proto_machine_stream_proto_msgTypes,
	}.Build()
	File_proto_machine_stream_proto = out.File
	file_proto_machine_stream_proto_goTypes = nil
	file_proto_machine_stream_proto_depIdxs = nil
}
